// ============================================================================
// RecallForge — AI Batch Import Schema (Canonical v1)
// ============================================================================
// Validates cards generated by ChatGPT, OpenClaw, scripts, spreadsheets.
// Supports JSON, JSONL, CSV, TSV — all normalized to this schema.
// ============================================================================

import { z } from 'zod';

// ─── Version ───────────────────────────────────────────────────────────────

export const AI_IMPORT_VERSION = 'recallforge-ai-import-v1' as const;

// ─── Shared enums ──────────────────────────────────────────────────────────

export const ConceptualPrioritySchema = z.enum(['low', 'medium', 'high', 'critical']);
export const ConceptualDifficultySchema = z.enum(['easy', 'medium', 'hard', 'very_hard']);

// ─── Duplicate strategy ────────────────────────────────────────────────────

export const AIDuplicateStrategySchema = z.enum([
  'skip',
  'update',
  'create_always',
  'merge_tags',
]);

export type AIDuplicateStrategy = z.infer<typeof AIDuplicateStrategySchema>;

// ─── Single import item ────────────────────────────────────────────────────

export const AIImportItemSchema = z.object({
  noteType: z.string().min(1, 'noteType es obligatorio'),
  deck: z.string().min(1, 'deck es obligatorio'),
  fields: z.record(z.string(), z.string()).refine(
    (vals) => Object.keys(vals).length > 0 && Object.values(vals).some(v => v.trim().length > 0),
    { message: 'Al menos un campo debe tener contenido' }
  ),
  tags: z.array(z.string().min(1)).optional().default([]),
  source: z.string().optional(),
  sourceMetadata: z.record(z.string(), z.unknown()).optional(),
  externalId: z.string().optional(),
  duplicateKey: z.string().optional(),
  // Academic classification fields
  subject: z.string().optional(),
  module: z.string().optional(),
  chapter: z.string().optional(),
  topic: z.string().optional(),
  subtopic: z.string().optional(),
  sourcePage: z.string().optional(),
  examScope: z.string().optional(),
  professor: z.string().optional(),
  book: z.string().optional(),
  className: z.string().optional(),
  lectureDate: z.string().optional(),
  aiGenerated: z.boolean().optional(),
  aiReviewStatus: z.enum(['pending-review', 'reviewed', 'corrected']).optional(),
  // Phase 2: Priority and conceptual difficulty
  priority: ConceptualPrioritySchema.optional(),
  conceptualDifficulty: ConceptualDifficultySchema.optional(),
  // Phase 2: Curriculum program name (for auto-resolution)
  program: z.string().optional(),
});

export type AIImportItem = z.infer<typeof AIImportItemSchema>;

// ─── Full file schema (JSON envelope) ──────────────────────────────────────

export const AIImportFileSchema = z.object({
  version: z.literal(AI_IMPORT_VERSION),
  items: z.array(AIImportItemSchema).min(1, 'Se requiere al menos un ítem'),
});

export type AIImportFile = z.infer<typeof AIImportFileSchema>;

// ─── Cloze validation helper ───────────────────────────────────────────────

const CLOZE_REGEX = /\{\{c\d+::.+?\}\}/;

export function validateClozeFields(
  noteTypeName: string,
  fields: Record<string, string>
): string | null {
  const isCloze = /cloze/i.test(noteTypeName);
  if (!isCloze) return null;

  const allText = Object.values(fields).join(' ');
  if (!CLOZE_REGEX.test(allText)) {
    return 'El tipo cloze requiere al menos una eliminación {{c1::...}} en los campos';
  }
  return null;
}

// ─── Validate a single item with cloze check ──────────────────────────────

export function validateImportItem(
  raw: unknown,
  index: number
): { data: AIImportItem; errors: string[] } {
  const errors: string[] = [];
  const result = AIImportItemSchema.safeParse(raw);

  if (!result.success) {
    for (const issue of result.error.issues) {
      errors.push(`[${index}] ${issue.path.join('.')}: ${issue.message}`);
    }
    return { data: raw as AIImportItem, errors };
  }

  const clozeError = validateClozeFields(result.data.noteType, result.data.fields);
  if (clozeError) {
    errors.push(`[${index}] ${clozeError}`);
  }

  return { data: result.data, errors };
}

// ─── Import options ────────────────────────────────────────────────────────

export const AIImportOptionsSchema = z.object({
  duplicateStrategy: AIDuplicateStrategySchema.default('skip'),
  batchSize: z.number().int().min(1).max(500).default(25),
  dryRun: z.boolean().default(false),
  defaultDeck: z.string().optional(),
  defaultNoteType: z.string().optional(),
  tagPrefix: z.string().optional(),
  // Academic defaults applied to all items missing these fields
  defaultSubject: z.string().optional(),
  defaultModule: z.string().optional(),
  defaultChapter: z.string().optional(),
  autoCreateDecks: z.boolean().default(true),
  // Phase 2: Curriculum integration
  defaultPriority: ConceptualPrioritySchema.optional(),
  defaultConceptualDifficulty: ConceptualDifficultySchema.optional(),
  autoCreateCurriculum: z.boolean().default(false),
  defaultProgram: z.string().optional(),
});

export type AIImportOptions = z.infer<typeof AIImportOptionsSchema>;
