// Bundles the in-chat study widget (src/widget) into one self-contained HTML
// string at src/lib/mcp/widget.generated.ts, served as the MCP App resource.
import { build } from 'esbuild';
import fs from 'fs';
import path from 'path';

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const result = await build({
  entryPoints: [path.join(root, 'src/widget/main.ts')],
  bundle: true,
  minify: true,
  format: 'esm',
  target: 'es2022',
  platform: 'browser',
  write: false,
  alias: { '@': path.join(root, 'src') },
  logLevel: 'warning',
});
const js = result.outputFiles[0].text.replace(/<\/script/gi, '<\\/script');
const css = fs.readFileSync(path.join(root, 'src/widget/styles.css'), 'utf8');
const html = `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>RecallForge</title><style>${css}</style></head><body><div id="app" class="rf"></div><script type="module">${js}</script></body></html>`;
const out = `// Generated by scripts/build-widget.mjs — do not edit. Run "npm run build:widget".\nexport const STUDY_WIDGET_HTML = ${JSON.stringify(html)};\n`;
fs.writeFileSync(path.join(root, 'src/lib/mcp/widget.generated.ts'), out);
console.log(`widget: ${(html.length / 1024).toFixed(0)} KB`);
